name: fin_data_warehouse
services:
  data-acquisition:
    build: data-acquisition
    container_name: acquisition
    environment:
      - FRED_API_KEY=${FRED_API_KEY}
      - CACHE_DIRECTORY=/app/cache
      - STAGING_DIRECTORY=/app/staging
    volumes:
      - ./staging:/app/staging
      - ./cache:/app/cache

  db:
    image: postgres:16
    container_name: database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - ./deploy/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER}
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 3s

  loader:
    build: data-loader
    container_name: loader
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - STAGING_DIRECTORY=/app/staging
    volumes:
      - ./staging:/app/staging
    depends_on:
      db:
        condition: service_healthy

  dbt:
    build: data-processing
    container_name: dbt
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - SEEDS_DIRECTORY=seeds
    volumes:
      - ./staging:/app/seeds
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_db:
