name: finance_db
version: 1.0.0
config-version: 2

profile: postgres

seed-paths: ["{{ env_var('SEEDS_DIRECTORY', '../data-staging') }}"]
model-paths: [models]
target-path: target

models:
  finance_db:
    dwh:
      +materialized: table
      +schema: dwh
    stg:
      +materialized: table
      +schema: stg

seeds:
  finance_db:
    wse_tickers_info:
      +column_types:
        volume: numeric
        firstTradeDateMilliseconds: numeric
        earningsTimestamp: numeric
        earningsTimestampStart: numeric
        earningsTimestampEnd: numeric
        compensationAsOfEpochDate: numeric
        governanceEpochDate: numeric
        enterpriseValue: numeric
        totalRevenue: numeric
        ebitda: numeric
        totalCash: numeric
        totalDebt: numeric
        freeCashflow: numeric
        operatingCashflow: numeric
        sharesShortPreviousMonthDate: numeric
        sharesOutstanding: numeric
        regularMarketTime: numeric
        nonDilutedMarketCap: numeric
        nextFiscalYearEnd: numeric
        netIncomeToCommon: numeric
        mostRecentQuarter: numeric
        marketCap: numeric
        lastSplitDate: numeric
        lastFiscalYearEnd: numeric
        lastDividendDate: numeric
        impliedSharesOutstanding: numeric
        grossProfits: numeric
        floatShares: numeric
        exDividendDate: numeric
        earningsCallTimestampStart: numeric
        earningsCallTimestampEnd: numeric
        dividendDate: numeric
        dateShortInterest: numeric

        