name: finance_db
version: 1.0.0
config-version: 2

profile: postgres

model-paths: [models]
target-path: target

models:
  finance_db:
    dwh:
      +materialized: table
      +schema: dwh

snapshots:
  finance_db:
    +target_schema: snapshots
