postgres:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: pgpass
      port: 5432
      dbname: finance_db
      # This is fallback value. It is needed in profiles.yml file, but will be overriden by schema names in dbt_project.yml
      schema: public
