name: fin_data_warehouse
services:
  data-acquisition:
    build: ../data-acquisition
    container_name: data_acquisition
    environment:
      - FRED_API_KEY=${FRED_API_KEY}
      - CACHE_DIRECTORY=/home/acqu/app/cache
      - STAGING_DIRECTORY=/home/acqu/app/staging
    volumes:
      - ../staging:/home/acqu/app/staging
      - ../cache:/home/acqu/app/cache

  db:
    image: postgres:16
    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER}
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 3s


  dbt:
    build: ../data-processing
    container_name: data_processing
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=db
      - SEEDS_DIRECTORY=seeds
    volumes:
      - ../data-staging:/app/seeds
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_db:
