name: fin_data_warehouse_test
services:
  data-acquisition:
    entrypoint: ["echo", "Acquisition disabled in test environment"]

  loader:
    volumes:
    # Select path to parquets created for tests
      - ../staging:/app/staging