CREATE SCHEMA IF NOT EXISTS dwh;
CREATE SCHEMA IF NOT EXISTS raw;

CREATE USER benchmark;

GRANT USAGE ON SCHEMA dwh TO benchmark;
GRANT SELECT ON ALL TABLES IN SCHEMA dwh TO benchmark;
ALTER DEFAULT PRIVILEGES IN SCHEMA dwh GRANT SELECT ON TABLES TO benchmark;

CREATE USER tableau;
GRANT USAGE ON SCHEMA dwh TO tableau;
GRANT SELECT ON ALL TABLES IN SCHEMA dwh TO tableau;
ALTER DEFAULT PRIVILEGES IN SCHEMA dwh GRANT SELECT ON TABLES TO tableau;
